const express = require('express');
const { asyncHandler } = require('../middleware/errors');
const auth = require('../controllers/auth');
const notifications = require('../controllers/notifications');
const controller = require('../controllers/academy-workflow');
const { authenticate, allowRoles } = require('../middleware/auth');
const adminManagement = require('../controllers/admin-management');
const security = require('../controllers/security');
const content = require('../controllers/content');
const { uploadMedia } = require('../middleware/mediaUpload');
const { uploadPhoto } = require('../middleware/photoUpload');
const registration = require('../controllers/registration');
const applications = require('../controllers/applications');

const router = express.Router();
router.post('/auth/login', asyncHandler(auth.login));
router.post('/auth/request-password-reset', asyncHandler(auth.requestPasswordReset));
router.post('/auth/reset-password', asyncHandler(auth.resetPassword));
router.post('/auth/register/request-otp', asyncHandler(registration.requestOtp));
router.get('/auth/register/batches', asyncHandler(registration.listBatches));
router.post('/auth/register/verify-otp', uploadPhoto, asyncHandler(registration.verifyOtp));
router.patch('/auth/application/:id/resubmit', asyncHandler(applications.resubmit));
router.get('/auth/me', authenticate, asyncHandler(auth.me));
router.post('/auth/change-password', authenticate, asyncHandler(auth.changePassword));
router.patch('/auth/admin-account', authenticate, allowRoles('admin'), asyncHandler(auth.updateAdminAccount));
router.get('/security/logs', authenticate, allowRoles('admin'), asyncHandler(security.listLogs));
router.get('/admin/applications', authenticate, allowRoles('admin'), asyncHandler(applications.list));
router.post('/admin/applications/:id/review', authenticate, allowRoles('admin'), asyncHandler(applications.review));
router.delete('/admin/applications/:id', authenticate, allowRoles('admin'), asyncHandler(applications.remove));
router.get('/content/settings', asyncHandler(content.getSettings));
router.patch('/content/settings', authenticate, allowRoles('admin'), asyncHandler(content.updateBranding));
router.post('/content/settings/asset', authenticate, allowRoles('admin'), uploadMedia, asyncHandler(content.uploadBrandAsset));
router.get('/content/media', authenticate, asyncHandler(content.listMedia));
router.post('/content/media', authenticate, allowRoles('admin'), uploadMedia, asyncHandler(content.uploadMedia));
router.delete('/content/media/:id', authenticate, allowRoles('admin'), asyncHandler(content.deleteMedia));
// Keep compatibility with older APK builds that used kind-specific delete paths.
router.delete('/content/videos/:id', authenticate, allowRoles('admin'), asyncHandler(content.deleteMedia));
router.delete('/content/files/:id', authenticate, allowRoles('admin'), asyncHandler(content.deleteMedia));
router.use('/students', require('./students'));
router.use('/attendance', require('./attendance'));
router.use('/physical-training-results', require('./physical-training-results'));
router.use('/physical-training-sheets', require('./physical-training-sheets'));
router.use('/', require('./academy'));
router.use('/tests', require('./tests'));
router.get('/notices', authenticate, asyncHandler(controller.listNotices));
router.post('/notices', authenticate, allowRoles('admin'), asyncHandler(controller.createNotice));
router.patch('/notices/:id', authenticate, allowRoles('admin'), asyncHandler(controller.updateNotice));
router.delete('/notices/:id', authenticate, allowRoles('admin'), asyncHandler(controller.deleteNotice));
router.get('/fees', authenticate, asyncHandler(controller.getFees));
router.get('/fees/summary', authenticate, allowRoles('admin'), asyncHandler(controller.feeSummary));
router.post('/fees', authenticate, allowRoles('admin'), asyncHandler(controller.createFee));
router.patch('/fees/:id', authenticate, allowRoles('admin'), asyncHandler(adminManagement.updateFee));
router.delete('/fees/:id', authenticate, allowRoles('admin'), asyncHandler(adminManagement.deleteFee));
router.post('/fees/:id/payments', authenticate, allowRoles('admin'), asyncHandler(controller.recordPayment));
router.get('/notifications', authenticate, asyncHandler(notifications.list));
router.patch('/notifications/:id/read', authenticate, asyncHandler(notifications.markRead));
router.delete('/notifications/:id', authenticate, allowRoles('admin'), asyncHandler(notifications.remove));

module.exports = router;
