const express = require('express');
const { asyncHandler } = require('../middleware/errors');
const auth = require('../controllers/auth');
const notifications = require('../controllers/notifications');
const controller = require('../controllers/academy-workflow');
const { authenticate, allowRoles } = require('../middleware/auth');
const adminManagement = require('../controllers/admin-management');
const security = require('../controllers/security');
const content = require('../controllers/content');
const { uploadMedia } = require('../middleware/mediaUpload');

const router = express.Router();
router.post('/auth/login', asyncHandler(auth.login));
router.post('/auth/request-password-reset', asyncHandler(auth.requestPasswordReset));
router.post('/auth/reset-password', asyncHandler(auth.resetPassword));
router.get('/auth/me', authenticate, asyncHandler(auth.me));
router.post('/auth/change-password', authenticate, asyncHandler(auth.changePassword));
router.patch('/auth/admin-account', authenticate, allowRoles('admin'), asyncHandler(auth.updateAdminAccount));
router.get('/security/logs', authenticate, allowRoles('admin'), asyncHandler(security.listLogs));
router.get('/content/settings', asyncHandler(content.getSettings));
router.patch('/content/settings', authenticate, allowRoles('admin'), asyncHandler(content.updateBranding));
router.post('/content/settings/asset', authenticate, allowRoles('admin'), uploadMedia, asyncHandler(content.uploadBrandAsset));
router.get('/content/media', authenticate, asyncHandler(content.listMedia));
router.post('/content/media', authenticate, allowRoles('admin'), uploadMedia, asyncHandler(content.uploadMedia));
router.use('/students', require('./students'));
router.use('/attendance', require('./attendance'));
router.use('/', require('./academy'));
router.use('/tests', require('./tests'));
router.get('/notices', authenticate, asyncHandler(controller.listNotices));
router.post('/notices', authenticate, allowRoles('admin'), asyncHandler(controller.createNotice));
router.get('/fees', authenticate, asyncHandler(controller.getFees));
router.post('/fees', authenticate, allowRoles('admin'), asyncHandler(controller.createFee));
router.patch('/fees/:id', authenticate, allowRoles('admin'), asyncHandler(adminManagement.updateFee));
router.delete('/fees/:id', authenticate, allowRoles('admin'), asyncHandler(adminManagement.deleteFee));
router.post('/fees/:id/payments', authenticate, allowRoles('admin'), asyncHandler(controller.recordPayment));
router.get('/notifications', authenticate, asyncHandler(notifications.list));
router.patch('/notifications/:id/read', authenticate, asyncHandler(notifications.markRead));

module.exports = router;
